version: '1.0.{build}'
image: 
  - Visual Studio 2019

branches:
  only:
  - master

init:
  - cmd: choco install dotnetcore-sdk
  - cmd: dotnet --version
  - cmd: dotnet --list-runtimes
  - cmd: dotnet --list-sdks
  - cmd: git config --global core.autocrlf true

before_build:
  - cmd: dotnet restore ./src/Melt/Melt.csproj --verbosity m

build_script:
  - cmd: dotnet publish ./src/Melt/Melt.csproj

clone_depth: 1

artifacts:
 - path: './built/Release/netcoreapp2.2/publish'
   name: Melt
   type: WebDeployPackage

test_script:
  - cmd: cd ./test/Melt.UnitTest
  - cmd: dotnet restore #./test/Melt.UnitTest/Melt.UnitTest.csproj --verbosity m
  - cmd: dotnet test
deploy:
  - provider: GitHub
    auth_token:
      secure: bF3InONSrgUawJPTjpPHNhsgvwv3SvkoWwRcWP4gq+Odk1ZhqNF0A1aQVvDKyAwE
    artifact: /.*\.zip/           
    draft: false
    prerelease: false
    on:
      branch: master

on_finish :