version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
build_script:
- cmd: dotnet publish ./src/Melt.csproj
test_script:
- cmd: "cd ./test/\ndotnet restore \ndotnet test"
artifacts:
- path: .\src\bin\Release\netcoreapp2.2\publish\
  name: Melt
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: WAfIsXkzH0DOMQ3//IB7Xp4PC8YCAr0TME4cqwcpodyNI2j+Fmg7La6Q9Wiw92oQ
  artifact: /.*\.zip/